name: Build and deploy Github pages

on:
  push:
    branches:
      - master
    pull_request:
      paths:
        - '*.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install docgen
        run: |
          curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh
          chmod +x install.sh
          ./install.sh
          rm install.sh
      
      - name: Create HTML and Markdown build directories
        run: mkdir -p build/{html,md}

      - name: Generate HTML docs from Postman collection
        run: docgen build -i off-pm-collection.json -e off-pm-env.json -o build/html/index.html

      - name: Generate Markdown docs from Postman collection
        run: docgen build -i off-pm-collection.json -e off-pm-env.json -o build/md/index.md -m

      - name: Commit generated documentation to current branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: .
          file_pattern: build/**/*
          commit_message: Update API documentation
          commit_options: '--no-verify --signoff'

      - name: Deploy HTML docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event_name == "pull_request" && "gh-pages-dev" || "gh-pages"}} # <- Branch on which commit will be made
          folder: build/html/  # <- Folder containing our generated HTML docs
