name: Build and deploy Github pages

on:
  push:
    branches:
      - master
      - deploy-*
    pull_request:
      paths:
        - '*.json'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node v12
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Install docgen
        run:
          curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh
          sudo chmod +x install.sh
          sudo ./install.sh
          rm install.sh

      - name: Generate documentation from Postman collection
        run:
          docgen build -i Open\ Food\ Facts\ API\ Documentation.postman_collection.json -o build/html/index.html

      - name: Generate documentation as Markdown
        run:
          docgen build -i Open\ Food\ Facts\ API\ Documentation.postman_collection.json -o build/md/index.md -m 

      - name: Deploy Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages      # <- Branch on which commit will be made
          folder: build/html/  # <- Folder containing our generated HTML docs

      - name: Commit Markdown documentation
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: gh-pages
          repository: .
          file_pattern: build/md/index.md
          commit_message: Update Markdown documentation
          commit_options: '--no-verify --signoff'

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          base: gh-pages
          delete-branch: true
          commit-message: Update API documentation
          title: Update API documentation
          body: API documentation changes pushed to branch gh-pages by GitHub Actions

