name: Test and build collection

on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
        
      - name: Install docgen
        run: curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh && sudo chmod +x install.sh && sudo ./install.sh && rm install.sh

      - name: Run docgen
        run: pwd

      - name: Run docgen
        run: docgen build -i /home/runner/work/api-documentation/api-documentation/Open Food Facts API Documentation.postman_collection.json -o index.html

      - name: Upload Doc
        uses: actions/upload-artifact@v2.2.4
        with:
          name: API Doc
          path: |
            /home/runner/work/api-documentation/api-documentation/index.html
      
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: Open Food Facts API Documentation.postman_collection.json
          reporters: cli
