name: Build and test Postman collection

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    name: Build documentation
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install docgen
        run: curl https://raw.githubusercontent.com/thedevsaddam/docgen/v3/install.sh -o install.sh && chmod +x install.sh && ./install.sh && rm install.sh

      - name: Generate HTML documentation
        run: docgen build -i "off-pm-collection.json" -o index.html

      - name: Generate Markdown documentation
        run: docgen build -i "off-pm-collection.json" -o index.md -m

      - name: Deploy HTML docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event_name == 'pull_request' && 'gh-pages-dev' || 'gh-pages'}} # <- Branch on which commit will be made
          folder: .  # <- Folder containing our generated HTML docs

      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}

  test:
    name: Run API integration tests
    runs-on: ubuntu-18.04
    steps:
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: off-pm-collection.json
          environment: off-pm-env.json
          reporters: cli
